import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import WorkExperience from "../components/WorkExperience";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div
      className={
        "bg-[rgba(36,36,36)] text-white h-screen" +
        " snap-y snap-mandatory overflow-y-scroll overflow-x-hidden" +
        " z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#02a9f7] scrollbar-thin"
      }
    >
      <Head>
        <title>Saif Mohamed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id={"hero"} className={"snap-start"}>
        <Hero />
      </section>

      <section id={"about"} className={"snap-center"}>
        <About />
      </section>

      <section id={"experience"} className={"snap-center"}>
        <WorkExperience />
      </section>

      <section id={"skills"} className={"snap-start"}>
        <Skills />
      </section>

      <section id="projects" className="snap-start">
        <Projects />
      </section>

      <section id="contact" className="snap-start">
        <Contact />
      </section>

      <Link href={"#hero"}>
        <footer className={"sticky bottom-5 right-5 w-full cursor-pointer"}>
          <div className={"flex items-center justify-center"}>
            <img
              className={
                "h-10 w-10 object-cover rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
              }
              src={
                "https://cdn.sanity.io/images/w8smplyk/production/7c0908a2f0e9281d32f5f25bbc5c023887505a7a-1920x1080.jpg"
              }
              alt={"Footer Logo"}
            />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;
